
### REGISTER USER
POST http://localhost:3100/register
Content-Type: application/json

{
    "cohort_no": "25",
    "firstName": "MR.LARUSO",
    "lastName": "MaKNON",
    "email": "LARUSO.mAKNON@thejitu.com",
    "password": "atopGUY"
}


### GET ALL MEMBERS
GET http://localhost:3100/members



####GET ONE MEMBER
GET http://localhost:3100/members/0e200028-2e2b-4ab7-8a72-964cd0938365



###  UPDATE A MEMBER
PUT  http://localhost:3100/update/0e200028-2e2b-4ab7-8a72-964cd0938365

Content-Type: application/json
{
    "cohort_no": "766",
    "firstName": "maxIL0ll",
    "lastName": "MAINA",
    "email": "adamlol.maina@thejitu.com",
    "password": "atopgfdgfwudan"
}



###DELETE USER

DELETE http://localhost:3100/delete/e01c927e-1f8d-4163-a309-66490d7b96e8


